### ISSUE TITLE
collectAsStateWithLifecycle() causes error

### ISSUE THREAD

**Issue by atick-faisal** [atick-faisal/Jetpack-Compose-Starter#206]
```
      Fatal Exception: java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
       at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1.invoke(LocalLifecycleOwner.kt:9)
       at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1.invoke(LocalLifecycleOwner.kt:1)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
       at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:3)
       at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:1)
       at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:16)
       at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:5)
       at androidx.lifecycle.compose.FlowExtKt.collectAsStateWithLifecycle(FlowExt.kt:15)
       at dev.atick.compose.ui.JetpackAppKt$JetpackApp$1$1.invoke(JetpackApp.kt:68)
       at dev.atick.compose.ui.JetpackAppKt$JetpackApp$1$1.invoke(JetpackApp.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at dev.atick.core.ui.components.BackgroundKt$AppGradientBackground$1.invoke(Background.kt:234)
       at dev.atick.core.ui.components.BackgroundKt$AppGradientBackground$1.invoke(Background.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:241)
       at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:177)
       at dev.atick.core.ui.components.BackgroundKt.AppGradientBackground(Background.kt:247)
       at dev.atick.compose.ui.JetpackAppKt$JetpackApp$1.invoke(JetpackApp.kt:81)
       at dev.atick.compose.ui.JetpackAppKt$JetpackApp$1.invoke(JetpackApp.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at dev.atick.core.ui.components.BackgroundKt$AppBackground$1$1.invoke(Background.kt:24)
       at dev.atick.core.ui.components.BackgroundKt$AppBackground$1$1.invoke(Background.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at dev.atick.core.ui.components.BackgroundKt$AppBackground$1.invoke(Background.kt:54)
       at dev.atick.core.ui.components.BackgroundKt$AppBackground$1.invoke(Background.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:241)
       at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:177)
       at dev.atick.core.ui.components.BackgroundKt.AppBackground(Background.kt:206)
       at dev.atick.compose.ui.JetpackAppKt.JetpackApp(JetpackApp.kt:97)
       at dev.atick.compose.MainActivity$onCreate$3$2.invoke(MainActivity.kt:47)
       at dev.atick.compose.MainActivity$onCreate$3$2.invoke(MainActivity.kt:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:90)
       at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:41)
       at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:286)
       at dev.atick.core.ui.theme.ThemeKt$JetpackTheme$1.invoke(Theme.kt:30)
       at dev.atick.core.ui.theme.ThemeKt$JetpackTheme$1.invoke(Theme.kt:9)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at dev.atick.core.ui.theme.ThemeKt.JetpackTheme(Theme.kt:400)
       at dev.atick.compose.MainActivity$onCreate$3.invoke(MainActivity.kt:85)
       at dev.atick.compose.MainActivity$onCreate$3.invoke(MainActivity.kt:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:36)
       at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:36)
       at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:282)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:40)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:1)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:42)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:153)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:45)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:9)
       at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:18)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:138)
       at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:9)
       at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:16)
       at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:25)
       at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:11)
       at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:1)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:1)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:2)
       at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:7)
       at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:8)
       at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:1)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:1)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:1)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:1)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:2)
       at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:109)
       at android.view.View.dispatchAttachedToWindow(View.java:22874)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3362)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2836)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10145)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
       at android.view.Choreographer.doFrame(Choreographer.java:945)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8674)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
```

**Comment by atick-faisal** [comment]
https://issuetracker.google.com/issues/336842920
